[pytest]
# directory for test discovery
testpaths = core
# pattern for test file discovery
python_files = *.test.py
# import mode (LET PYTHON CORRECTLY IMPORT MODULES named "xxx.test.py")
addopts = --import-mode=importlib
# nam pattrn of test runners
python_classes = Test*
python_functions = test_*