/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AddPlaylistIndexRouteImport } from './routes/add-playlist/index'
import { Route as PlaylistPlaylistIdIndexRouteImport } from './routes/playlist.$playlistId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlaylistIndexRoute = AddPlaylistIndexRouteImport.update({
  id: '/add-playlist/',
  path: '/add-playlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdIndexRoute = PlaylistPlaylistIdIndexRouteImport.update({
  id: '/playlist/$playlistId/',
  path: '/playlist/$playlistId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-playlist/': typeof AddPlaylistIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/playlist/$playlistId/': typeof PlaylistPlaylistIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-playlist': typeof AddPlaylistIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-playlist/': typeof AddPlaylistIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/playlist/$playlistId/': typeof PlaylistPlaylistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-playlist/' | '/settings/' | '/playlist/$playlistId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-playlist' | '/settings' | '/playlist/$playlistId'
  id:
    | '__root__'
    | '/'
    | '/add-playlist/'
    | '/settings/'
    | '/playlist/$playlistId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPlaylistIndexRoute: typeof AddPlaylistIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  PlaylistPlaylistIdIndexRoute: typeof PlaylistPlaylistIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-playlist/': {
      id: '/add-playlist/'
      path: '/add-playlist'
      fullPath: '/add-playlist/'
      preLoaderRoute: typeof AddPlaylistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId/': {
      id: '/playlist/$playlistId/'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId/'
      preLoaderRoute: typeof PlaylistPlaylistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPlaylistIndexRoute: AddPlaylistIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  PlaylistPlaylistIdIndexRoute: PlaylistPlaylistIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
